### ISSUE TITLE
Siema, podalbys swojego dc? Potrzebuje pomocy, bo co chwile crashuje gierke, nie moge nic zrobic!

### ISSUE THREAD

**Issue by patrysiako** [SiekamCebule/sj-sim#5]
.

**Comment by KonradKrol** [comment]
Witam. Taka już natura Sj.Sima, że się co chwilę crashuje :)
Podaję discorda społeczności: https://discord.gg/pwVWz5AFCf
Mój nick to "siekamcebule"

Swoją drogą, zaczęły się prace nad nowym projektem - grze w stylu Football Managera. Także na moim GitHubowym profilu
